image: docker

services:
  - docker

stages:
  - test

before_script:
  - echo 'testinh' 

backend-test-job:
  stage: test
  before_script:
    - cd backend
    - apk add --no-cache docker-compose
  script:
    - docker-compose run --entrypoint "npm run unittest" backend